/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import DAO.FornecedorDAO;
import Externos.Drawer;
import Externos.DrawerItem;
import Externos.EventDrawer;
import Externos.Header;
import java.awt.Color;
import javax.swing.ImageIcon;
import Externos.*;
import Modelagem.Fornecedor;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.extras.*;
import com.formdev.flatlaf.demo.FlatLafDemo.*;
import com.formdev.flatlaf.demo.*;
import Externos.TextField;
import java.awt.Font;

/**
 *
 * @author 0062928
 */
public class TelaVenda extends javax.swing.JFrame {

    private DrawerController drawer;

   

    public TelaVenda() {
        initComponents();
        drawer = Drawer.newDrawer(this)
                .background(new Color(90, 90, 90))
                .closeOnPress(true)
                .backgroundTransparent(0.3f)
                .leftDrawer(true)
                .enableScroll(true)
                .enableScrollUI(false)
                .headerHeight(160)
                .header(new Header())
                .space(3)
                
                .addChild(new DrawerItem("Produtos").icon(new ImageIcon(getClass().getResource("/icon/income.png"))).build())
                .addChild(new DrawerItem("Ingredientes").icon(new ImageIcon(getClass().getResource("/icon/expense.png"))).build())
                .addChild(new DrawerItem("Vendas").icon(new ImageIcon(getClass().getResource("/icon/report.png"))).build())
                .addChild(new DrawerItem("Funcionarios").icon(new ImageIcon(getClass().getResource("/icon/user.png"))).build())
                .addChild(new DrawerItem("Fornecedores").icon(new ImageIcon(getClass().getResource("/icon/data.png"))).build())
                .event(new EventDrawer() {
                    @Override
                    public void selected(int index, DrawerItem item) {
                     if(index == 0){
                        
                        dispose();
                        TelaProduto t = new TelaProduto();
                        t.setVisible(true);
                        t.setLocationRelativeTo(null);
                     }
                     if(index == 1){
                        dispose();
                        TelaIngrediente t = new TelaIngrediente();
                        t.setVisible(true);
                        t.setLocationRelativeTo(null);
                     }
                     if(index == 2){
                        dispose();
                        TelaVenda t = new TelaVenda();
                        t.setVisible(true);
                        t.setLocationRelativeTo(null);
                     }
                     if(index == 3){
                        dispose();
                        TelaFuncionario t = new TelaFuncionario();
                        t.setVisible(true);
                        t.setLocationRelativeTo(null);
                     }
                     if(index == 4){
                        dispose();
                        TelaVenda t = new TelaVenda();
                        t.setVisible(true);
                        t.setLocationRelativeTo(null);
                     }
                     
                    }
                    
                })
                .build();
        
        tabelaListagem.setShowHorizontalLines(true);
        tabelaListagem.setShowVerticalLines(true);
        tabelaListagem.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 11));
        tabelaListagem.getTableHeader().setOpaque(false);
        tabelaListagem.getTableHeader().setBackground(new Color(32, 136, 203));
        tabelaListagem.getTableHeader().setForeground(new Color(255, 255, 255));
        tabelaListagem.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaListagem = new javax.swing.JTable();
        txtPesquisar = new swing.TextFieldAnimation();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        button2 = new swing.Button();
        button3 = new swing.Button();
        button4 = new swing.Button();
        button5 = new swing.Button();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        btnSalvar4.setBackground(new java.awt.Color(0, 119, 234));
        btnSalvar4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnSalvar4.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar4.setText("Salvar");
        btnSalvar4.setBorder(null);
        btnSalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Produto", "Preço", "Qtd", "SubTotal"
            }
        ));
        tabelaListagem.setFocusable(false);
        tabelaListagem.setGridColor(new java.awt.Color(230, 230, 230));
        jScrollPane3.setViewportView(tabelaListagem);
        if (tabelaListagem.getColumnModel().getColumnCount() > 0) {
            tabelaListagem.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 500, 247));

        txtPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPesquisar.setAnimationColor(new java.awt.Color(51, 102, 255));
        txtPesquisar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        txtPesquisar.setHintText("Pesquisar Cliente ...");
        txtPesquisar.setSelectionColor(new java.awt.Color(51, 102, 255));
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 32));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel2.setText("Data:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        jLabel12.setText("Consumidor:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 50, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 50, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel16.setText("Total Venda:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 90, 40));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        button2.setBackground(new java.awt.Color(86, 127, 253));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Finalizar Venda");
        button2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, 40));

        button3.setBackground(new java.awt.Color(86, 127, 253));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Pesquisar Produto");
        button3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 140, 40));

        button4.setBackground(new java.awt.Color(86, 127, 253));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("Cancelar Produtos");
        button4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 140, 40));

        button5.setBackground(new java.awt.Color(86, 127, 253));
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setText("Cancelar Venda");
        button5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 140, 40));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel17.setText("Cód Venda:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 820, 360));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/TelaVenda.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        

    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar4;
    private swing.Button button2;
    private swing.Button button3;
    private swing.Button button4;
    private swing.Button button5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tabelaListagem;
    private swing.TextFieldAnimation txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
